### ISSUE TITLE
ADD: Update docs to the latest version

### ISSUE THREAD

**Issue by Thorian1te** [xchainjs/xchainjs.github.io#13]
Udpate repo with latest chain examples and to be reflected in documentation

**Comment by NotoriousLisp** [comment]
<img width="908" alt="Screen Shot 2022-04-23 at 4 58 10 PM" src="https://user-images.githubusercontent.com/9355927/164947297-d8d35bbd-069b-4119-a4f8-678b34b9888b.png">

Looks like the "Retrieve seed" section needs an updated code example showing how to implement `getSeed()`.  Should I open a new issue or this good enough here?
